name: auto-code-rover
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - ld_impl_linux-64
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.2.0
  - pip=23.3.1
  - python=3.11.7
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023d
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - loguru=0.7.2
  - rich=13.7.1
  - pip:
      - -r requirements.txt
